- id: doi:10.1101/2025.07.24.666596
  image: images/VPT_et_al_2025_preprin_fig6.png
  publisher: bioRxiv


- id: doi:10.1093/molbev/msae061
  image: https://oup.silverchair-cdn.com/oup/backfile/Content_public/Journal/mbe/41/4/10.1093_molbev_msae061/5/m_msae061f1.jpeg?Expires=1756161567&Signature=lBwxBnQz15ZhNt8ct~qKdigQ3rOugrF1VocNOLWib2CArzSV1rHkTo1s0xC79r3Zx33sy5bHIvgh-EVbezFbPjZXdhlYzGAoGfc4~YhBpkLF4jYkEakZ9g~axbNGkUEjgkJwVxp6~CtLvhLaUVSt-xeF4fXmhcb317U0Obp38vZOxS2oKlTp7FDA3zCsdJlyyE-PSnZ-6udmYgO-ICx0liDfaRUEdcO43pDkkXAtHnKqnYhKY51KqXR0W3pPMbBADK-z3R89lGTH8OYwq~VfNFznHIWpM7jvSp0K~6Yu~MeSr93if9Y5HRVtnrbLJ4LkLC0KKZAA2jOTpTOFoHXbLA__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA

- id: doi:10.1126/science.adk5518
  image: https://www.science.org/cms/10.1126/science.adk5518/asset/aeaafbdb-8044-46ac-a2ce-883732b65a5a/assets/images/large/science.adk5518-f5.jpg
  buttons:
    - type: video
      text: Genome Engineering Seminar Series, Harvard Medical School
      link: https://harvard.zoom.us/rec/share/tW3rf2DicOHHGOxrN-KJAa7WhR72y--stX6fsl91yIOjBuUWF-RtYlVPjf40YI34.-NpLqh6eJZwlwhE4
    - type: media
      text: A CRISPR Tool for Tinkering with the Human Transcriptome, <em>The Scientist</em>
      link: https://www.the-scientist.com/a-crispr-tool-for-tinkering-with-the-human-transcriptome-72019


- id: doi:10.1126/sciadv.adj8277
  image: images/2023_SciAdv_cover.png
  buttons:
    - type: media
      text: CRISPR-Based Editing of RNA Viruses Developed, <em>Inside Precision Medicine</em>
      link: https://www.insideprecisionmedicine.com/topics/precision-medicine/crispr-based-editing-of-rna-viruses-developed/
    - type: media
      text: RNA editing set to democratise viral engineering, <em>Chemistry World</em>
      link: https://www.chemistryworld.com/news/this-is-just-the-beginning-rna-editing-set-to-democratise-viral-engineering/4018149.article
    - type: podcast
      text: Discussion on TWiV 1045 (from 34:11)
      link: https://www.microbe.tv/twiv/twiv-1045/

- id: doi:10.3390/v14092009
  image: https://www.mdpi.com/viruses/viruses-14-02009/article_deploy/html/images/viruses-14-02009-g001-550.jpg


- id: doi:10.1016/j.celrep.2021.109197
  image: https://www.cell.com/cms/attachment/a15cff63-6055-4e7c-80b4-fc85f356acae/fx1.jpg
  buttons:
    - type: media 
      text: MSU researchers publish study on coronavirus variant, <em>MSU News Service</em>
      link: https://www.montana.edu/news/21206/msu-researchers-publish-study-on-coronavirus-variant

- id: doi:10.1016/j.xcrm.2021.100319
  image: https://ars.els-cdn.com/content/image/1-s2.0-S2666379121001622-fx1.jpg

- id: doi:10.1016/j.xcrm.2020.100098
  image: https://ars.els-cdn.com/content/image/1-s2.0-S2666379120X00073-cov200h.gif
  buttons:
    - type: media 
      text: Sewers Are Now a COVID-19 Early-Warning System, <em>The Atlantic</em>
      link: https://www-stage.theatlantic.com/health/archive/2020/09/tracking-coronavirus-through-sewage/615958/
  

- id: doi:10.1038/s41467-022-35445-5
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fs41467-022-35445-5/MediaObjects/41467_2022_35445_Fig3_HTML.png?as=webp

- id: doi:10.1038/s41594-018-0173-y
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fs41594-018-0173-y/MediaObjects/41594_2018_173_Fig3_HTML.png?as=webp

- id: doi:10.1016/j.chom.2022.11.005
  image: https://ars.els-cdn.com/content/image/1-s2.0-S1931312822005613-gr1_lrg.jpg

- id: doi:10.1016/j.ymeth.2022.06.002
  image: https://ars.els-cdn.com/content/image/1-s2.0-S1046202322001244-ga1_lrg.jpg

- id: doi:10.1089/scd.2015.0204
  remove: true

- id: doi:10.1073/pnas.2216430120
  image: /images/pnas_secor.jpg

- id: 10.1016/j.gastha.2022.06.002
  style: none
